### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by gerroon** [nextcloud/news-updater#15]
Hi

I am on Debian Wheezy so I do not have Python3.5 therefo I compiled Python3.5 and trying to run news-updated with that version

/opt/python3.5/bin/python3.5 -m nextcloud_news_updater /var/www/NC

```
- Nextcloud News Updater - ERROR - Command '['php', '-f', '/var/www/NC/occ', 'news:updater:before-update']' returned non-zero exit status 1: Trying again in 30 seconds
Traceback (most recent call last):
  File "/opt/news-updater-master/nextcloud_news_updater/api/updater.py", line 69, in run
    self.before_update()
  File "/opt/news-updater-master/nextcloud_news_updater/api/cli.py", line 73, in before_update
    self.cli.run(self.api.before_cleanup_command)
  File "/opt/news-updater-master/nextcloud_news_updater/api/cli.py", line 12, in run
    return check_output(commands)
  File "/opt/python3.5/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/opt/python3.5/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['php', '-f', '/var/www/NC/occ', 'news:updater:before-update']' returned non-zero exit status 1
^CTraceback (most recent call last):
  File "/opt/news-updater-master/nextcloud_news_updater/api/updater.py", line 69, in run
    self.before_update()
  File "/opt/news-updater-master/nextcloud_news_updater/api/cli.py", line 73, in before_update
    self.cli.run(self.api.before_cleanup_command)
  File "/opt/news-updater-master/nextcloud_news_updater/api/cli.py", line 12, in run
    return check_output(commands)
  File "/opt/python3.5/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/opt/python3.5/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['php', '-f', '/var/www/NC/occ', 'news:updater:before-update']' returned non-zero exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/python3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/python3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/news-updater-master/nextcloud_news_updater/__main__.py", line 30, in <module>
    main()
  File "/opt/news-updater-master/nextcloud_news_updater/__main__.py", line 26, in main
    container.resolve(Updater).run()
  File "/opt/news-updater-master/nextcloud_news_updater/api/updater.py", line 99, in run
    time.sleep(30)

```

thanks

**Comment by BernhardPosselt** [comment]
Check your data/nextcloud.log after you ran it. You likely have a second php.ini for your CLI that is missing php extensions.

**Comment by BernhardPosselt** [comment]
See https://github.com/nextcloud/news-updater/issues/16 

Closing this as dup, please continue over there.
