### ISSUE TITLE
Error - before_update

### ISSUE THREAD

**Issue by meowIAmAUser** [nextcloud/news-updater#38]
My Feeds seem to not update and my Console gives me this Error:

2021-06-14 20:56:37,389 - Nextcloud News Updater - ERROR - 'NoneType' object has no attribute 'before_cleanup_url': Trying again in 30 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nextcloud_news_updater/api/updater.py", line 69, in run
    self.before_update()
  File "/usr/local/lib/python3.7/dist-packages/nextcloud_news_updater/api/web.py", line 75, in before_update
    'Calling before update url:  %s' % self.api.before_cleanup_url)
AttributeError: 'NoneType' object has no attribute 'before_cleanup_url'

How do I fix this?

**Comment by BernhardPosselt** [comment]
Can you try to install the update from master (see https://github.com/nextcloud/news-updater#manual-installation)? Not sure if it works properly for the current version yet.

**Comment by snauth** [comment]
Master fixes the problem.

**Comment by dvzrv** [comment]
@BernhardPosselt can you please release a new version? e7f51442581fb430cc52a3ccbfec920412ab5d65 introduced support for news >= 15.0.0

**Comment by BernhardPosselt** [comment]
@dvzrv let me add you as a collaborator on pypi so you can push updates, what's your account?

**Comment by dvzrv** [comment]
@BernhardPosselt I'm sorry, I don't think I have the time for a commitment like that. I maintain over 700 packages for Arch Linux.

**Comment by PaulRitzkat** [comment]
For those that have it running as a container, this is my quick and dirty fix:

**Dockerfile:**
```Dockerfile
FROM python:3-alpine

RUN apk add git;git clone https://github.com/nextcloud/news-updater;cd news-updater/;python3 setup.py install --install-scripts=/usr/bin;cd;rm -rf news-updater/;apk del git

CMD nextcloud-news-updater ${NEXTCLOUD_URL} --user ${NEXTCLOUD_ADMIN_USER} --password ${NEXTCLOUD_ADMIN_PASSWORD} --loglevel info
```
**docker-compose.yml:**
```docker-compose.yml
  news-updater:
    build: ./news-updater
    environment:
      NEXTCLOUD_URL: "https://my.nextcloud" 
      NEXTCLOUD_ADMIN_USER: "updater"
      NEXTCLOUD_ADMIN_PASSWORD: "password"
```

**Comment by Ablu** [comment]
Any chance to get a new release that includes this fix? :innocent:

**Comment by HLFH** [comment]
For ArchLinux, I submitted a package that works: https://aur.archlinux.org/packages/nextcloud-news-updater-git.

**Comment by msm-code** [comment]
Slightly updated dockerfile that works for me (it seems to be necessary to install setuptools now):

```dockerfile
FROM python:3-alpine

RUN apk add git;git clone https://github.com/nextcloud/news-updater;apk del git
RUN pip install setuptools
RUN cd news-updater; python3 setup.py install --install-scripts=/usr/bin

CMD nextcloud-news-updater ${NEXTCLOUD_URL} --user ${NEXTCLOUD_ADMIN_USER} --password ${NEXTCLOUD_ADMIN_PASSWORD} --loglevel info
```
