### ISSUE TITLE
MissingSectionHeaderError

### ISSUE THREAD

**Issue by hulliver** [nextcloud/news-updater#4]
nextcloud-news-updater --loglevel info -c /volume1/web/nextcloud/data/news/config/config.ini
Traceback (most recent call last):
  File "/bin/nextcloud-news-updater", line 11, in <module>
    load_entry_point('nextcloud-news-updater==9.0.2', 'console_scripts', 'nextcloud-news-updater')()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/**main**.py", line 26, in main
    container.resolve(Updater).run()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/dependencyinjection/container.py", line 67, in resolve
    result = factory(self)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/dependencyinjection/container.py", line 18, in **call**
    return self.factory(container)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/container.py", line 24, in _create_updater
    if container.resolve(Config).is_web():
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/dependencyinjection/container.py", line 67, in resolve
    result = factory(self)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/dependencyinjection/container.py", line 18, in __call__
    return self.factory(container)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/container.py", line 34, in _create_config
    config = config_parser.parse_file(args.config)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/nextcloud_news_updater/config.py", line 87, in parse_file
    successfully_parsed = parser.read(path)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/volume1/web/nextcloud/data/news/config/config.ini', line: 1
'autoPurgeMinimumInterval = 60\n'

**Comment by BernhardPosselt** [comment]
You are missing the section header in your config file, read the README again ;)

**Comment by hulliver** [comment]
config.ini 
autoPurgeMinimumInterval = 60
autoPurgeCount = 200
maxRedirects = 10
maxSize = 104857600
exploreUrl = 
feedFetcherTimeout = 60
useCronUpdates = false

**Comment by BernhardPosselt** [comment]
yes, your config is invalid.

**Comment by hulliver** [comment]
so
 autoPurgeMinimumInterval = 60
is not a section header?

**Comment by BernhardPosselt** [comment]
exactly, check the readme. Its the stuff in the square brackets

**Comment by BernhardPosselt** [comment]
ah LOL

**Comment by BernhardPosselt** [comment]
You are using the News app configuration for the updater. Thats not how it works, both have separate configs ;) (Seriously READ! the README ;))

**Comment by hulliver** [comment]
aha human stupidity is limitless... sorry
